### ISSUE TITLE
setup.sh: line 102:

### ISSUE THREAD

**Issue by Profitsarts** [digitoimistodude/dudestack#2]
Hi!
I get this error when I run setup.sh:

setup.sh: line 102: /Users/User/Projects/dudestack/createproject_generated.sh: No such file or directory
mv: rename /Users/User/Projects/dudestack/createproject_generated.sh to /usr/local/bin/createproject: No such file or directory
chmod: /usr/local/bin/createproject: No such file or directory

I think it's because don't really know what to enter here:
"Staging server home path"
"Staging server public path"

and there's no file as: /usr/local/bin/createproject

Sorry.... I'm so noob

**Comment by rollecode** [comment]
Hello and thanks for using dudestack! You are officiall the first user to throw an issue and a first user I actually know have tried dudestack outside of our company. 

Please provide a bit more information so we can help you better. And be specific.

- What operating system do you use?
- Have you read the documentation, especially [Requirements](https://github.com/digitoimistodude/dudestack#requirements)? dudestack requires you have Projects folder in your home directory and dudestack repository cloned into it.

Staging server means a test server, for example web hotel or VPS, but it's not related to those errors and it's not compulsory. It seems you have not followed the directions carefully enough and just tried to run the script.

Please provide more information and I'll help you through it.

**Comment by Profitsarts** [comment]
First of all, many thanks for replying.
Just discovered the Instructions repo, a minute after opened the issue :)

And sorry for being so limited in my explanation.

I am on OS X 10.11.6 and  I have the projects folder here: /Users/Myuser/Projects/profitsarts.com/dudestack

1. Could you give me an example of the Staging server, both public and home? I used **"/home/hostname/public_html/dev.profitsarts.com"** for public and **"/Users/Myuser/Projects/profitsarts.com"**

2. I dropped Trellis because I have  shared hosting and I really can't gettin' it to work properly. Then I bumped into Bedrock+Capistrano and yours, but yours looks more complete, maintained and witty.
Will I have problems connecting via SSH? I have shell access to my shared hosting, I can SSH with no issues via terminal, but when tried to provisioning through Ansible it always ended up being unable to connect to the server's IP. I've lost a whole week looking up in the forums... haha

Thanks a lot for the help!

**Comment by rollecode** [comment]
Thanks for the details. 

Dudestack is a quite massive package and a result for **years** of research and fine tuning. It's based on early version of bedrock and developed further on our own, including best bits of bedrock in the way. I'm glad you think it's more complete and maintained, even witty, haha, so do we. However, because of its *in development*-nature, on top of us only two (2) freelancers we know have successfully built projects with it.

Dudestack works a bit differently than trellis/bedrock, it's meant to be stand alone and modified. So actually what `createproject` does, it clones dudestack and needed packages and creates a project on top of it. So you **should not** have dudestack inside a project. Project kinda IS dudestack.

This can be all found from instructions but first just clone the repository to /Users/youruser/Projects/dudestack, then run setup.sh. After this you can start tweaking your createproject-script.

1. Staging server home and public can be anything, for example home can be **/home/youruser** (=where the deploy files go) and public **/var/www/**. For us the home dir is (asiakas means a customer in Finnish) **/var/www/asiakas.dude.fi/projects** and public **/var/www/asiakas.dude.fi/public_html** - in that way we can have project files in projects dir and public files in real webroot. You see, [Capistrano](http://capistranorb.com/documentation/overview/what-is-capistrano/) works in a way it links the release and other files from project directory. In that way you can have let's say 3 different versions of your project and just rollback to previous working release without having to deploy everything all over again if something goes south.

2. With shared hosting, it's sometimes a pain to use these kinds of development tools, we've tried that. Maybe should be noted that also in the docs, thanks for pointing it out. With shared hosting on remote server you will need shell access (SSH), git, appropriate permissions.

As you can see, not very easy to wrap everything up, I feel like typing another documentation here. Just try to follow the [dudestack-instructions here](https://github.com/digitoimistodude/dudestack-instructions), and if something fails, let me know! Going to close this for now, but just comment below if you need to.

**Comment by Profitsarts** [comment]
Thanks for the documentation add-on :)

I was an entire week having email conversations with my hosting to enable SSH but finally they say I can’t install Git.
It’s hilarious that I’ve spent quite a long time to get nothing… The silver lining is that I’ve learned  a lot, especially about terminal commands.
I’m more a old school designer in transition to code, you know… no that’s why I’m explaining like i’m five…

The point now is: I want to test things (my portfolio site in order to looking for a job) and don’t want to spend money (shared hosting is a friend’s)
Want to move to Heroku. I’ve read that it has problems with Trellis, but I found this to make it work fine with Bedrock: https://github.com/frc/bedrock-on-heroku

What do you think about Heroku and a free Dyno to host a tiny portfolio under Dudestack?
What’s about Trellis? I mean, why do you prefer Capistrano?
I did the whole process and it was good, unless when I was prompted to type Vagrant’s Password, which I don’t know and didn’t enter before anywhere I think. After “createproject” it started to ask me for it again
bash: line 0: cd: /var/www/profitsarts/: No such file or directory
bash: vendor/wp-cli/wp-cli/bin/wp: No such file or directory
vagrant@10.1.2.4's password: 

Installing WordPress...:
vagrant@10.1.2.4's password: 
bash: line 0: cd: /var/www/profitsarts/: No such file or directory
bash: vendor/wp-cli/wp-cli/bin/wp: No such file or directory
Removing default WordPress posts...:

So… I’m kind of stuck…

Edit: Email replied text

**Comment by rollecode** [comment]
Yeah, I'm sure it's a lot to take in. I didn't expect that someone would use dudestack for a study purpose, hats off to you sir!

Trellis was born after bedrock, so I haven't even tried it. Roots had ansible cookbooks earlier, but I think ansible for web or WordPress is *waaaayy* too complicated and far-fetched, or then I just don't get it. Deploying with Capistrano is in my opinion more fastforward and tied with shell/bash-commands which I like a lot. I can program Capistrano to do stuff I'd have to do manually without it. Just one `cap deploy staging` or `cap deploy production` command and it fetches the files to remote server from git, runs composer and other possible stuff, links the files and boom you're done. And like I said before, I think there's no rollback-system in other ways, in Capistrano it's exceptionally good and straightforward.

Shared hosting packages can be really pain in the arse with their limitations (usually you cannot install *any* software that doesn't come with the package), but that's why they are so cheap. To be honest, I have never tried dudestack on free platforms or Heroku, but if you have a patient learning curve, I really recommend [Digital Ocean](https://www.digitalocean.com/pricing/) VPS, it starts from only 5 USD per month (less than Spotify or Netflix!). They have really good tutorials how to start your own web servers or to install server components. Or even better, build your droplet using [ServerPilot](https://serverpilot.io/), it's like "click and go" type of droplet for Digital Ocean VPS.

I presume you have installed our vagrant machine, [marlin-vagrant](https://github.com/digitoimistodude/marlin-vagrant) successfully, following 100% the directions? you should pair it to your computer to never having to input password. Default password is `vagrant`, all explained [here](https://github.com/digitoimistodude/marlin-vagrant).

Because the documentation is so vast and things are changing, there might be some mistakes. I cannot be sure and don't remember by heart which point was what, so I'd have to test the whole process from scratch and no time to do that now, but I hope this comment helps you to move forward.

Remember, you should always use the tools you *feel like are for you*, be it bedrock or Trellis.

**Comment by Profitsarts** [comment]
I followed the Dudestack instructions 100%.
When It asks for Vagrant's type, I chose Marlin, and I guessed it installs  marlin-vagrant automatically and completely...
Or Do I have to Install it before from its own repo and follow the instructions to later get to install Dudestack?

Thanks again

**Comment by rollecode** [comment]
Yes, it has to be installed before, it's one of the requirements you should complete before going though dudestack instructions. Sorry if not making this clear enough.
